#
# Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
PREFIX yang: <http://www.typefox.io/yang/Yang#>
PREFIX yang-config: <http://www.typefox.io/yang/Yang#Config/>
PREFIX yang-pres: <http://www.typefox.io/yang/Yang#Presence/>
PREFIX yang-stmt: <http://www.typefox.io/yang/Yang#Statement/>
PREFIX yang2: <http://huawei.com/kg/def/yang/>

CONSTRUCT {
  ?target_stmt_iri yang2:hasPresence ?presence .
  ?target_stmt_iri yang2:hasConfig ?config .
}
FROM <http://www.typefox.io/yang/common>
FROM <http://huawei.com/kg/def/common/yang>
WHERE {
  OPTIONAL {
    ?stmt_iri yang-stmt:substatements ?presence_iri .
    ?presence_iri a yang:Presence .
    ?resence_iri yang-pres:description ?presence .
  }
  OPTIONAL {
    ?stmt_iri yang-stmt:substatements ?config_iri .
    ?config_iri a yang:Config .
    ?config_iri yang-config:isConfig ?config .
  }
}
